#!/usr/bin/env bash
#
# Build the React frontend against the current CDK stack outputs and upload
# it to the S3 bucket that CloudFront serves.
#
# WHY THIS EXISTS:
#   `cdk_deploy.sh` creates the S3 bucket + CloudFront distribution but does NOT
#   upload the frontend. An empty bucket behind CloudFront returns 403
#   AccessDenied — which is exactly what shows in the browser after a fresh deploy.
#   This script closes that gap.
#
# WHAT THIS SCRIPT DOES:
#   1. Reads aws/cdk/cdk-outputs.json for the freshly-deployed UserPool,
#      Client, ApiEndpoint, bucket name, and CloudFront distribution id.
#   2. Regenerates medmcqa/webapp/frontend/.env.production with those values
#      (the existing file is stale from a prior SAM deploy and bakes wrong ids).
#   3. Runs `npm ci && npm run build` in the frontend dir.
#   4. `aws s3 sync dist/ s3://$BUCKET --delete`
#   5. Issues a CloudFront invalidation for `/*` so edge caches fetch the new bundle.
#   6. Probes https://dl.mdaie-sutd.fit for HTTP 200.
#
# Flags:
#   --skip-build   Re-upload the existing dist/ without rebuilding (fast; assumes env vars match).
#   --no-invalidate   Skip the CF invalidation (costs $0.005 per 1000 paths beyond the free tier).
#
# Usage:
#   bash aws/deploy_frontend.sh
#   bash aws/deploy_frontend.sh --skip-build
#
# Output → aws/deploy_frontend.log

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
FRONTEND_DIR="$PROJECT_DIR/medmcqa/webapp/frontend"
OUTPUTS="$SCRIPT_DIR/cdk/cdk-outputs.json"
LOG="$SCRIPT_DIR/deploy_frontend.log"
: > "$LOG"

SKIP_BUILD=0
NO_INVALIDATE=0
for arg in "$@"; do
    case "$arg" in
        --skip-build)    SKIP_BUILD=1 ;;
        --no-invalidate) NO_INVALIDATE=1 ;;
        -h|--help)
            grep -E "^#( |$)" "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *) echo "Unknown flag: $arg (use --help)"; exit 2 ;;
    esac
done

log()  { echo "[$(date -u +%FT%TZ)] $*" | tee -a "$LOG"; }
fail() { log "FATAL: $*"; log "See $LOG"; exit 1; }
run()  { log "+ $*"; eval "$@" 2>&1 | tee -a "$LOG"; return ${PIPESTATUS[0]}; }

log "=== Frontend deploy ==="
log "Frontend dir: $FRONTEND_DIR"

# ── 1. Load creds + stack outputs ──────────────────────────────────────────────
ENV_FILE="$SCRIPT_DIR/cdk/.env"
[[ -f "$ENV_FILE" ]] || fail ".env not found at $ENV_FILE"
set -a; source "$ENV_FILE"; set +a
export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-ap-southeast-1}"

[[ -f "$OUTPUTS" ]] || fail "cdk-outputs.json not found — run bash aws/cdk_deploy.sh first"

USER_POOL_ID=$(python3 -c "import json; print(json.load(open('$OUTPUTS'))['MedMCQAStack']['UserPoolId'])")
USER_POOL_CLIENT_ID=$(python3 -c "import json; print(json.load(open('$OUTPUTS'))['MedMCQAStack']['UserPoolClientId'])")
API_ENDPOINT=$(python3 -c "import json; print(json.load(open('$OUTPUTS'))['MedMCQAStack']['ApiEndpoint'])")
BUCKET=$(python3 -c "import json; print(json.load(open('$OUTPUTS'))['MedMCQAStack']['FrontendBucketName'])")

log "UserPoolId:       $USER_POOL_ID"
log "UserPoolClientId: $USER_POOL_CLIENT_ID"
log "ApiEndpoint:      $API_ENDPOINT"
log "Bucket:           $BUCKET"

# Look up the CloudFront distribution id by its alias so we can invalidate it
DIST_ID=$(aws cloudfront list-distributions \
    --query "DistributionList.Items[?Aliases.Items[?@=='dl.mdaie-sutd.fit']].Id | [0]" \
    --output text 2>>"$LOG" || echo "")
[[ -n "$DIST_ID" && "$DIST_ID" != "None" ]] || fail "Could not find CloudFront distribution for dl.mdaie-sutd.fit"
log "CloudFront DistId: $DIST_ID"

# ── 2. Regenerate .env.production ──────────────────────────────────────────────
ENV_PROD="$FRONTEND_DIR/.env.production"
log ""
log "--- Writing $ENV_PROD ---"
cat > "$ENV_PROD" <<EOF
# Generated by aws/deploy_frontend.sh on $(date -u +%FT%TZ)
# DO NOT EDIT BY HAND — rerun deploy_frontend.sh after any CDK deploy that
# changes UserPool / Client / ApiEndpoint.

VITE_REGION=ap-southeast-1
VITE_USER_POOL_ID=$USER_POOL_ID
VITE_USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID
VITE_API_ENDPOINT=$API_ENDPOINT
EOF
cat "$ENV_PROD" | tee -a "$LOG"

# ── 3. Build ───────────────────────────────────────────────────────────────────
cd "$FRONTEND_DIR" || fail "cd $FRONTEND_DIR failed"

if [[ $SKIP_BUILD -eq 0 ]]; then
    log ""
    log "--- npm install ---"
    if [[ ! -d node_modules ]]; then
        run "npm ci" || run "npm install" || fail "npm install failed"
    else
        log "node_modules present — skipping install"
    fi

    log ""
    log "--- npm run build ---"
    run "npm run build" || fail "npm run build failed"
else
    log "--- SKIP-BUILD: using existing dist/ ---"
fi

[[ -d dist && -f dist/index.html ]] || fail "dist/index.html missing — build must have failed"
log "Built assets:"
ls -la dist/ | tee -a "$LOG"

# ── 4. Sync to S3 ──────────────────────────────────────────────────────────────
log ""
log "--- aws s3 sync dist/ s3://$BUCKET --delete ---"
# Long-lived cache for hashed assets, no-cache for index.html so the SPA picks
# up new bundle refs immediately.
run "aws s3 sync dist/ s3://$BUCKET --delete \
    --cache-control 'public,max-age=31536000,immutable' \
    --exclude 'index.html' \
    --exclude 'uploads/*'" || fail "s3 sync (assets) failed"

run "aws s3 cp dist/index.html s3://$BUCKET/index.html \
    --cache-control 'public,max-age=0,must-revalidate' \
    --content-type 'text/html'" || fail "s3 cp index.html failed"

# ── 5. CloudFront invalidation ─────────────────────────────────────────────────
if [[ $NO_INVALIDATE -eq 0 ]]; then
    log ""
    log "--- CloudFront invalidation ---"
    INV_ID=$(aws cloudfront create-invalidation \
        --distribution-id "$DIST_ID" \
        --paths '/*' \
        --query 'Invalidation.Id' --output text 2>>"$LOG") \
        || fail "invalidation request failed"
    log "Invalidation: $INV_ID (propagation typically 1–5 min)"
fi

# ── 6. Probe ───────────────────────────────────────────────────────────────────
log ""
log "--- Probe ---"
URL="https://dl.mdaie-sutd.fit"
sleep 10
CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 15 "$URL/" || echo "000")
log "GET $URL/ → HTTP $CODE"
if [[ "$CODE" == "200" ]]; then
    log "Frontend deploy SUCCESSFUL ✓"
elif [[ "$CODE" == "403" ]]; then
    log "Still 403 — edge cache hasn't updated yet. Retry in 2-5 min or check CloudFront status."
else
    log "Unexpected HTTP $CODE. Check CloudFront distribution status: aws cloudfront get-distribution --id $DIST_ID"
fi

log ""
log "=== FRONTEND DEPLOY COMPLETE ==="
log "URL:     $URL"
log "Bucket:  s3://$BUCKET"
log "DistId:  $DIST_ID"
log "Log:     $LOG"
